# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.6.8"
  name: hcl2json
  go_mod: github.com/tmccombs/${{ name }}
  go_build: go build -v -buildmode=pie -trimpath -modcacherw -ldflags "-X main.version=${{ version }}"
  go_bin: ${{ "%PREFIX%\\bin\\" ~ name ~ ".exe" if win else "$PREFIX/bin/" ~ name }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://${{ go_mod }}/archive/v${{ version }}.tar.gz
  sha256: 681ef77f32b86a065158575997c48420be148dd4308c4e0bea9c3e617b0f4047
  target_directory: ${{ go_mod }}

build:
  number: 1
  script:
    env:
      GOPATH: ${{ SRC_DIR }}
    content:
      - cd ${{ go_mod }}
      - ${{ go_build }} -o "${{ go_bin }}"
      - go-licenses save . --save_path "${{ SRC_DIR }}/thirdparty" --ignore ${{ go_mod }}

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - requirements:
      run:
        - ripgrep
    script:
      content:
        - hcl2json --version
        - if: not win
          then: hcl2json --version | rg '${{ version }}'

about:
  homepage: https://pkg.go.dev/${{ go_mod }}
  summary: Convert hcl2 to json
  license: Apache-2.0
  license_file:
    - ${{ go_mod }}/LICENSE
    - thirdparty/
  repository: https://${{ go_mod }}

extra:
  recipe-maintainers:
    - dhirschfeld
    - bollwyvl
